name: DMS Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      rabbitmq:
        image: rabbitmq
        ports:
        - 5672:5672
        options: '--health-cmd "rabbitmqctl status" --health-interval 10s --health-timeout 10s --health-retries 6 --health-start-period 60s'
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Create secret
      shell: bash
      working-directory: ./CM.Integration.Tests/secrets
      run: |
        echo -e "$APP_SECRET_TEST"
        echo -e "$APP_SECRET_TEST" > appsettings.json
      env:
        APP_SECRET_TEST: ${{ secrets.APP_SECRET_TEST }}

    - name: Install dependencies
      run: dotnet restore CaseManagement.sln
    - name: Build
      run: dotnet build CaseManagement.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore
      working-directory: CM.Integration.Tests
