export default {
  generalDisputeItems: ['futureHearings', 'missingKeyFileInfo', 'missingDisputeNotice', 'noticeNotProvided', 'emailWithErrors', 'incompleteTasks', 'unpaidFees', 'evidenceOverrideOn'],
  documentAndDeliveryItems: ['incompleteOutcomeDocuments', 'notReadyDeliveredDocuments', 'undeliveredDocuments', 'incompleteDocumentRequests', 'incompleteSubServiceRequests', 'documentsMissingDeliveries'],
  hearingOutcomeItems: ['missingIssueOutcomes', 'missingHearingParticipations', 'missingHearingDetails', 'missingNoticeService', 'missingNoticeServiceConfirmations', 'missingDocumentWritingTime', 'missingEvidenceService'],
  /* General Dispute Completeness Items */
  futureHearings: {
    title: 'Future hearing',
    sub_title: 'Future Hearings should be unassigned when a dispute is closed',
    help: 'A count of all future hearing still on the dispute (with start date later than the time the check was run). Closed files should not have a future hearing, participatory files that are processed during intake should have a future hearing.',
    link: 'hearing_item',
    show_io: false,
    show_office: false,
    show_adjudicator: true,
    show_arb: true
  },
  missingKeyFileInfo: {
    title: 'Missing key file Info',
    help: 'Indicates if a dispute file does not have any respondents, does not have any issues, or is missing the primary applicant address. This is key information that is entered manually from paper applications.',
    link: 'overview_item',
    show_io: true,
    show_office: false,
    show_adjudicator: false,
    show_arb: false
  },
  missingDisputeNotice: {
    title: 'Missing initial dispute notice',
    help: 'A count of all notices of dispute resolution proceeding or amendment notices that are missing notice service information.',
    link: 'notice_item',
    show_io: true,
    show_office: false,
    show_adjudicator: false,
    show_arb: false
  },
  noticeNotProvided: {
    title: 'Any notice not indicated as provided',
    help: 'A count of notices or amendments that are not indicated as provided. All notices must be indicated as provided as this is important to system functionality and reporting timeframes',
    link: 'notice_item',
    show_io: true,
    show_office: false,
    show_adjudicator: false,
    show_arb: false,
  },
  emailWithErrors: {
    title: 'Emails with send errors',
    help: 'A count of emails that failed to be passed to the email server from DMS and are showing a send error message. These should try to be resent, especially if they contain important information that has associated timeframes.',
    link: 'communication_item',
    show_io: true,
    show_office: true,
    show_adjudicator: false,
    show_arb: false,
  },
  incompleteTasks: {
    title: 'Incomplete tasks',
    help: 'A count of all tasks that are not marked as completed (currently active) for all user types. Important when closing a file, or when completing tasks on a file.',
    link: 'task_item',
    show_io: true,
    show_office: true,
    show_adjudicator: true,
    show_arb: true,
  },
  unpaidFees: {
    title: 'Unpaid fees',
    help: 'A count of unpaid dispute fees. All fees on a dispute file should be completed, especially the initial application fee as it is important to system functionality and reporting.',
    link: 'payment_item',
    show_io: true,
    show_office: false,
    show_adjudicator: false,
    show_arb: false,
  },
  evidenceOverrideOn: {
    title: 'Evidence override On',
    help: 'Whether or not the evidence override is currently turned on. It should always be turned off unless there is a reason it is open or submissions can be made into a file that is no longer being worked on and become an unknown part of the permanent file.',
    link: 'overview_item',
    show_io: true,
    show_office: true,
    show_adjudicator: true,
    show_arb: true,
  },
  /* Document And Delivery Completeness Items */
  incompleteOutcomeDocuments: {
    title: 'Outcome documents missing uploaded files',
    help: 'A count of outcome documents with no final PDF file uploaded and a final PDF file needs to be uploaded.',
    link: 'document_item',
    show_io: true,
    show_office: false,
    show_adjudicator: true,
    show_arb: true,
  },
  notReadyDeliveredDocuments: {
    title: 'Outcome documents not ready to deliver',
    help: 'A count of documents where ready to deliver is set to true, but the document is not indicated as sent.',
    link: 'document_item',
    show_io: true,
    show_office: false,
    show_adjudicator: true,
    show_arb: true,
  },
  undeliveredDocuments: {
    title: 'Outcome documents with undelivered documents',
    help: 'A count of documents where ready to deliver is set to true, but the document is not indicated as sent.',
    link: 'document_item',
    show_io: true,
    show_office: true,
    show_adjudicator: false,
    show_arb: false,
  },
  incompleteDocumentRequests: {
    title: 'Incomplete document requests (CCR)',
    help: 'A count of correction, clarification or review requests that do not have a final status entered.',
    link: 'document_item',
    show_io: false,
    show_office: false,
    show_adjudicator: true,
    show_arb: true,
  },
  incompleteSubServiceRequests: {
    title: 'Incomplete substituted service requests',
    help: 'A count of substituted service requests that are not completed.',
    link: 'overview_item',
    show_io: true,
    show_office: false,
    show_adjudicator: true,
    show_arb: false,
  },
  documentsMissingDeliveries: {
    title: 'Outcome documents missing deliveries',
    help: 'A count of documents that have been added to an outcome document group that do not have at least one associated delivery record created.',
    link: 'document_item',
    show_io: true,
    show_office: false,
    show_adjudicator: true,
    show_arb: true,
  },
  /* Hearing outcome items*/
  missingIssueOutcomes: {
    title: 'Missing issue outcomes',
    help: 'A count of issues where the issue outcomes are not set (arb outcome). This count also includes any issue outcomes set to \'Not Decided\'.',
    link: 'overview_item',
    show_io: false,
    show_office: false,
    show_adjudicator: true,
    show_arb: true,
  },
  missingHearingParticipations: {
    title: 'Missing hearing participations',
    help: 'A count of total hearing participations records on the dispute file that have missing hearing participation information.',
    link: 'hearing_item',
    show_io: false,
    show_office: false,
    show_adjudicator: true,
    show_arb: true,
  },
  missingHearingDetails: {
    title: 'Missing hearing details',
    help: 'A count of hearings that are missing hearing prep time and method information.',
    link: 'hearing_item',
    show_io: false,
    show_office: false,
    show_adjudicator: true,
    show_arb: true,
  },
  missingNoticeService: {
    title: 'Missing notice service',
    help: 'A count of all notices of dispute resolution proceeding or amendment notices that are missing notice service information.',
    link: 'notice_item',
    show_io: false,
    show_office: false,
    show_adjudicator: true,
    show_arb: true,
  },
  missingNoticeServiceConfirmations: {
    title: 'Missing notice service confirmations',
    help: 'A count of all served and not served notice service records that have not been confirmed.',
    link: 'notice_item',
    show_io: false,
    show_office: false,
    show_adjudicator: true,
    show_arb: false,
  },
  missingDocumentWritingTime: {
    title: 'Missing document writing time',
    help: 'A count of outcome document sets that are missing writing time or other required processing information.',
    link: 'document_item',
    show_io: false,
    show_office: false,
    show_adjudicator: true,
    show_arb: true,
  },
  missingEvidenceService: {
    title: 'Missing evidence service',
    help: 'A count of evidence service records that are missing service information.',
    link: 'notice_item',
    show_io: false,
    show_office: false,
    show_adjudicator: false,
    show_arb: false,
  }
}