// <auto-generated />
using System;
using CM.Data.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CM.Data.Model.Migrations
{
    [DbContext(typeof(CaseManagementContext))]
    [Migration("20180529083533_AddUsersAndRoles")]
    partial class AddUsersAndRoles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CM.Data.Model.Dispute", b =>
                {
                    b.Property<int>("DisputeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<byte?>("CreationMethod");

                    b.Property<Guid?>("CrossAppDisputeGuid");

                    b.Property<int?>("CrossAppFileNumber");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<byte?>("DisputeSubType");

                    b.Property<byte?>("DisputeType");

                    b.Property<byte?>("DisputeUrgency");

                    b.Property<byte?>("EvidenceOverride");

                    b.Property<int?>("FileNumber");

                    b.Property<int?>("InitialPaymentBy");

                    b.Property<DateTime?>("InitialPaymentDate");

                    b.Property<bool?>("IsAmended");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<DateTime?>("OriginalNoticeDate");

                    b.Property<bool?>("OriginalNoticeDelivered");

                    b.Property<int?>("OriginalNoticeId");

                    b.Property<int?>("PetDamageDepositAmount");

                    b.Property<string>("RentPaymentInterval")
                        .HasMaxLength(100);

                    b.Property<int?>("SecurityDepositAmount");

                    b.Property<int?>("SubmittedBy");

                    b.Property<DateTime?>("SubmittedDate");

                    b.Property<string>("TenancyAddress")
                        .HasMaxLength(80);

                    b.Property<string>("TenancyCity")
                        .HasMaxLength(50);

                    b.Property<string>("TenancyCountry")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("TenancyEndDate");

                    b.Property<byte?>("TenancyEnded");

                    b.Property<byte?>("TenancyGeozoneId");

                    b.Property<DateTime?>("TenancyStartDate");

                    b.Property<string>("TenancyZipPostal")
                        .HasMaxLength(7);

                    b.HasKey("DisputeId");

                    b.ToTable("Disputes");
                });

            modelBuilder.Entity("CM.Data.Model.DisputeStatus", b =>
                {
                    b.Property<int>("DisputeStatusId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("DisputeGuid");

                    b.Property<int?>("DurationSeconds");

                    b.Property<int?>("Owner");

                    b.Property<byte?>("Process");

                    b.Property<byte?>("Stage");

                    b.Property<byte>("Status");

                    b.Property<string>("StatusNote")
                        .HasMaxLength(255);

                    b.Property<string>("StatusSetBy")
                        .HasMaxLength(100);

                    b.Property<DateTime>("StatusStartDate");

                    b.HasKey("DisputeStatusId");

                    b.HasIndex("DisputeGuid");

                    b.ToTable("DisputeStatuses");
                });

            modelBuilder.Entity("CM.Data.Model.DisputeUser", b =>
                {
                    b.Property<int>("DisputeUserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<bool>("IsActive");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int?>("ParticipantId");

                    b.Property<int>("SystemUserId");

                    b.HasKey("DisputeUserId");

                    b.HasIndex("DisputeGuid");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("SystemUserId");

                    b.ToTable("DisputeUsers");
                });

            modelBuilder.Entity("CM.Data.Model.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AcceptedTOU");

                    b.Property<DateTime?>("AcceptedTOUDate");

                    b.Property<string>("AccessCode")
                        .HasMaxLength(10);

                    b.Property<string>("Address")
                        .HasMaxLength(125);

                    b.Property<string>("BusinessContactFirstName")
                        .HasMaxLength(50);

                    b.Property<string>("BusinessContactLastName")
                        .HasMaxLength(70);

                    b.Property<string>("BusinessName")
                        .HasMaxLength(100);

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .HasMaxLength(50);

                    b.Property<byte?>("CountryId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<bool?>("EmailVerified");

                    b.Property<string>("Fax")
                        .HasMaxLength(15);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsAmended");

                    b.Property<bool?>("IsDeleted");

                    b.Property<string>("LastName")
                        .HasMaxLength(70);

                    b.Property<string>("MailAddres")
                        .HasMaxLength(125);

                    b.Property<string>("MailCity")
                        .HasMaxLength(50);

                    b.Property<string>("MailCountry")
                        .HasMaxLength(50);

                    b.Property<string>("MailPostalZip")
                        .HasMaxLength(15);

                    b.Property<string>("MailProvinceState")
                        .HasMaxLength(50);

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<bool?>("NoEmail");

                    b.Property<byte?>("PackageDeliveryMethod");

                    b.Property<byte>("ParticipantStatus");

                    b.Property<byte?>("ParticipantType");

                    b.Property<string>("PostalZip")
                        .HasMaxLength(15);

                    b.Property<byte?>("PrimaryContactMethod");

                    b.Property<string>("PrimaryPhone")
                        .HasMaxLength(15);

                    b.Property<string>("PrimaryPhoneExtension")
                        .HasMaxLength(4);

                    b.Property<byte?>("PrimaryPhoneType");

                    b.Property<bool?>("PrimaryPhoneVerified");

                    b.Property<string>("ProvinceState")
                        .HasMaxLength(50);

                    b.Property<byte?>("ProvinceStateId");

                    b.Property<string>("SecondaaryPhone")
                        .HasMaxLength(15);

                    b.Property<byte?>("SecondaryContactMethod");

                    b.Property<string>("SecondaryPhoneExtension")
                        .HasMaxLength(4);

                    b.Property<byte?>("SecondaryPhoneType");

                    b.Property<bool?>("SecondaryPhoneVerified");

                    b.Property<int?>("SystemUserId");

                    b.HasKey("ParticipantId");

                    b.HasIndex("DisputeGuid");

                    b.HasIndex("SystemUserId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("CM.Data.Model.SystemUser", b =>
                {
                    b.Property<int>("SystemUserId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("AcceptsTextMessages");

                    b.Property<string>("AccountEmail")
                        .HasMaxLength(100);

                    b.Property<string>("AccountMobile")
                        .HasMaxLength(15);

                    b.Property<bool>("AdminAccess");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("FullName")
                        .HasMaxLength(100);

                    b.Property<bool?>("IsActive");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Password")
                        .HasMaxLength(250);

                    b.Property<int>("SystemUserRoleId");

                    b.Property<Guid>("UserGuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("SystemUserId");

                    b.HasIndex("SystemUserRoleId");

                    b.ToTable("SystemUsers");
                });

            modelBuilder.Entity("CM.Data.Model.SystemUserRole", b =>
                {
                    b.Property<int>("SystemUserRoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleDescritption")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("SessionDuration");

                    b.HasKey("SystemUserRoleId");

                    b.ToTable("SystemUserRoles");
                });

            modelBuilder.Entity("CM.Data.Model.DisputeStatus", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("DisputeStatuses")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.DisputeUser", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("DisputeUsers")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CM.Data.Model.Participant", "Participant")
                        .WithMany("DisputeUsers")
                        .HasForeignKey("ParticipantId");

                    b.HasOne("CM.Data.Model.SystemUser", "SystemUser")
                        .WithMany("DisputeUsers")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.Participant", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("Participants")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CM.Data.Model.SystemUser", "SystemUser")
                        .WithMany("Participants")
                        .HasForeignKey("SystemUserId");
                });

            modelBuilder.Entity("CM.Data.Model.SystemUser", b =>
                {
                    b.HasOne("CM.Data.Model.SystemUserRole", "SystemUserRole")
                        .WithMany()
                        .HasForeignKey("SystemUserRoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
