// <auto-generated />
using System;
using CM.Data.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CM.Data.Model.Migrations
{
    [DbContext(typeof(CaseManagementContext))]
    [Migration("20180918114730_AddFieldsToClaimAndRemedy")]
    partial class AddFieldsToClaimAndRemedy
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CM.Data.Model.AccessCodeExcludeWord", b =>
                {
                    b.Property<int>("ExcludeWordId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ExcludeWord")
                        .HasMaxLength(6);

                    b.HasKey("ExcludeWordId");

                    b.ToTable("AccessCodeExcludeWords");
                });

            modelBuilder.Entity("CM.Data.Model.Amendment", b =>
                {
                    b.Property<int>("AmendmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AmendmentChangeHtml")
                        .IsRequired();

                    b.Property<byte>("AmendmentChangeType");

                    b.Property<string>("AmendmentDescription")
                        .HasMaxLength(255);

                    b.Property<int?>("AmendmentFileId");

                    b.Property<string>("AmendmentPendingData");

                    b.Property<byte?>("AmendmentSource");

                    b.Property<byte>("AmendmentStatus")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue((byte)0);

                    b.Property<int?>("AmendmentSubmitterId");

                    b.Property<string>("AmendmentTitle")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.Property<byte>("AmendmentTo");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<byte?>("IncludeInDecision");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int?>("NoticeId");

                    b.HasKey("AmendmentId");

                    b.HasIndex("AmendmentSubmitterId");

                    b.HasIndex("DisputeGuid");

                    b.HasIndex("NoticeId");

                    b.ToTable("Amendments");
                });

            modelBuilder.Entity("CM.Data.Model.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApiCallData")
                        .IsRequired();

                    b.Property<string>("ApiCallType")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<string>("ApiErrorResponse");

                    b.Property<string>("ApiName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ApiResponse")
                        .HasMaxLength(10);

                    b.Property<DateTime>("ChangeDate");

                    b.Property<Guid?>("DisputeGuid");

                    b.Property<string>("SubmitterName")
                        .HasMaxLength(50);

                    b.Property<int?>("SubmitterParticipantId");

                    b.Property<int>("SubmitterRole");

                    b.Property<int?>("SubmitterUserId");

                    b.HasKey("AuditLogId");

                    b.HasIndex("SubmitterParticipantId");

                    b.HasIndex("SubmitterUserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("CM.Data.Model.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte?>("ClaimCode");

                    b.Property<int>("ClaimGroupId");

                    b.Property<byte?>("ClaimSource");

                    b.Property<byte?>("ClaimStatus");

                    b.Property<byte?>("ClaimStatusReason");

                    b.Property<string>("ClaimTitle")
                        .HasMaxLength(150);

                    b.Property<byte?>("ClaimType");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool?>("IsAmended");

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("ClaimId");

                    b.HasIndex("ClaimGroupId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("CM.Data.Model.ClaimDetail", b =>
                {
                    b.Property<int>("ClaimDetailId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClaimId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<int>("DescriptionBy");

                    b.Property<string>("Impact")
                        .HasMaxLength(750);

                    b.Property<bool?>("IsAmended");

                    b.Property<bool?>("IsDeleted");

                    b.Property<string>("Location")
                        .HasMaxLength(255);

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<DateTime?>("NoticeDate");

                    b.Property<byte?>("NoticeMethod");

                    b.Property<string>("WhenAware")
                        .HasMaxLength(255);

                    b.HasKey("ClaimDetailId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("DescriptionBy");

                    b.ToTable("ClaimDetails");
                });

            modelBuilder.Entity("CM.Data.Model.ClaimGroup", b =>
                {
                    b.Property<int>("ClaimGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("ClaimGroupId");

                    b.HasIndex("DisputeGuid");

                    b.ToTable("ClaimGroups");
                });

            modelBuilder.Entity("CM.Data.Model.ClaimGroupParticipant", b =>
                {
                    b.Property<int>("ClaimGroupParticipantId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ClaimGroupId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<byte>("GroupParticipantRole");

                    b.Property<int?>("GroupPrimaryContactId");

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("ParticipantId");

                    b.HasKey("ClaimGroupParticipantId");

                    b.HasIndex("ClaimGroupId");

                    b.HasIndex("DisputeGuid");

                    b.HasIndex("ParticipantId");

                    b.ToTable("ClaimGroupParticipants");
                });

            modelBuilder.Entity("CM.Data.Model.CommonFile", b =>
                {
                    b.Property<int>("CommonFileId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CommonFileGuid");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("FileDescription")
                        .HasMaxLength(1000);

                    b.Property<string>("FileMimeType")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("FileSize");

                    b.Property<string>("FileTitle")
                        .HasMaxLength(100);

                    b.Property<byte?>("FileType");

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("CommonFileId");

                    b.ToTable("CommonFiles");
                });

            modelBuilder.Entity("CM.Data.Model.Dispute", b =>
                {
                    b.Property<int>("DisputeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<byte?>("CreationMethod");

                    b.Property<Guid?>("CrossAppDisputeGuid");

                    b.Property<int?>("CrossAppFileNumber");

                    b.Property<byte?>("CrossAppRole");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<byte?>("DisputeSubType");

                    b.Property<byte?>("DisputeType");

                    b.Property<byte?>("DisputeUrgency");

                    b.Property<int?>("FileNumber");

                    b.Property<int?>("InitialPaymentBy");

                    b.Property<DateTime?>("InitialPaymentDate");

                    b.Property<bool?>("IsAmended");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<DateTime?>("OriginalNoticeDate");

                    b.Property<bool?>("OriginalNoticeDelivered");

                    b.Property<int?>("OriginalNoticeId");

                    b.Property<int>("OwnerSystemUserId");

                    b.Property<decimal?>("PetDamageDepositAmount");

                    b.Property<decimal?>("RentPaymentAmount");

                    b.Property<string>("RentPaymentInterval")
                        .HasMaxLength(100);

                    b.Property<decimal?>("SecurityDepositAmount");

                    b.Property<int?>("SubmittedBy");

                    b.Property<DateTime?>("SubmittedDate");

                    b.Property<string>("TenancyAddress")
                        .HasMaxLength(80);

                    b.Property<DateTime?>("TenancyAgreementDate");

                    b.Property<byte?>("TenancyAgreementSignedBy");

                    b.Property<string>("TenancyCity")
                        .HasMaxLength(50);

                    b.Property<string>("TenancyCountry")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("TenancyEndDate");

                    b.Property<byte?>("TenancyEnded");

                    b.Property<byte?>("TenancyGeozoneId");

                    b.Property<DateTime?>("TenancyStartDate");

                    b.Property<string>("TenancyZipPostal")
                        .HasMaxLength(7);

                    b.HasKey("DisputeId");

                    b.HasIndex("OwnerSystemUserId");

                    b.ToTable("Disputes");
                });

            modelBuilder.Entity("CM.Data.Model.DisputeFee", b =>
                {
                    b.Property<int>("DisputeFeeId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("AmountDue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("AmountPaid");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<DateTime?>("DatePaid");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<DateTime?>("DueDate");

                    b.Property<string>("FeeDescription")
                        .HasMaxLength(255);

                    b.Property<byte?>("FeeType");

                    b.Property<bool?>("IsActive");

                    b.Property<bool?>("IsDeleted");

                    b.Property<bool?>("IsPaid");

                    b.Property<byte?>("MethodPaid");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int?>("PayorId");

                    b.HasKey("DisputeFeeId");

                    b.HasIndex("DisputeGuid");

                    b.ToTable("DisputeFees");
                });

            modelBuilder.Entity("CM.Data.Model.DisputeStatus", b =>
                {
                    b.Property<int>("DisputeStatusId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("DisputeGuid");

                    b.Property<int?>("DurationSeconds");

                    b.Property<byte?>("EvidenceOverride");

                    b.Property<int?>("Owner");

                    b.Property<byte?>("Process");

                    b.Property<byte?>("Stage");

                    b.Property<byte>("Status");

                    b.Property<string>("StatusNote")
                        .HasMaxLength(255);

                    b.Property<int>("StatusSetBy");

                    b.Property<DateTime>("StatusStartDate");

                    b.HasKey("DisputeStatusId");

                    b.HasIndex("DisputeGuid");

                    b.ToTable("DisputeStatuses");
                });

            modelBuilder.Entity("CM.Data.Model.DisputeUser", b =>
                {
                    b.Property<int>("DisputeUserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<bool>("IsActive");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int?>("ParticipantId");

                    b.Property<int>("SystemUserId");

                    b.HasKey("DisputeUserId");

                    b.HasIndex("DisputeGuid");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("SystemUserId");

                    b.ToTable("DisputeUsers");
                });

            modelBuilder.Entity("CM.Data.Model.EmailAttachment", b =>
                {
                    b.Property<int>("EmailAttachmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("AttachmentType");

                    b.Property<int?>("CommonFileId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int>("EmailMessageId");

                    b.Property<int?>("FileId");

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<DateTime?>("ReceivedDate");

                    b.Property<DateTime?>("SendDate");

                    b.HasKey("EmailAttachmentId");

                    b.HasIndex("CommonFileId");

                    b.HasIndex("EmailMessageId");

                    b.HasIndex("FileId");

                    b.ToTable("EmailAttachments");
                });

            modelBuilder.Entity("CM.Data.Model.EmailMessage", b =>
                {
                    b.Property<int>("EmailMessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("BodyType")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue((byte)1);

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid?>("DisputeGuid")
                        .IsRequired();

                    b.Property<string>("EmailFrom")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.Property<string>("EmailTo")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.Property<string>("HtmlBody")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<bool?>("IsDeleted");

                    b.Property<byte>("MessageType");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int?>("ParticipantId");

                    b.Property<DateTime?>("PreferedSendDate");

                    b.Property<DateTime?>("ReceivedDate");

                    b.Property<DateTime?>("ResponseDueDate");

                    b.Property<byte>("Retries")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue((byte)0);

                    b.Property<byte?>("SendStatus");

                    b.Property<DateTime?>("SentDate");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<byte>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue((byte)0);

                    b.Property<string>("TextBody");

                    b.HasKey("EmailMessageId");

                    b.HasIndex("DisputeGuid");

                    b.HasIndex("ParticipantId");

                    b.ToTable("EmailMessages");
                });

            modelBuilder.Entity("CM.Data.Model.EmailTemplate", b =>
                {
                    b.Property<int>("EmailTemplateId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<byte?>("DefaultRecipientGroup");

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("ReplyEmailAddress")
                        .HasMaxLength(100);

                    b.Property<string>("SubjectLine")
                        .HasMaxLength(150);

                    b.Property<byte?>("TemplateAccessRoles");

                    b.Property<int?>("TemplateAttachment01");

                    b.Property<int?>("TemplateAttachment02");

                    b.Property<int?>("TemplateAttachment03");

                    b.Property<int?>("TemplateAttachment04");

                    b.Property<string>("TemplateDescription")
                        .HasMaxLength(1000);

                    b.Property<string>("TemplateHtml");

                    b.Property<byte?>("TemplateStatus");

                    b.Property<string>("TemplateTitle")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte?>("TemplateType");

                    b.HasKey("EmailTemplateId");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("CM.Data.Model.File", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AddedBy");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<Guid>("FileGuid");

                    b.Property<string>("FileMimeType")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int?>("FilePackageId");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("FileSize");

                    b.Property<byte?>("FileStatus")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue((byte)0);

                    b.Property<string>("FileTitle")
                        .HasMaxLength(100);

                    b.Property<byte>("FileType")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue((byte)0);

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("FileId");

                    b.HasIndex("DisputeGuid");

                    b.HasIndex("FilePackageId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("CM.Data.Model.FileDescription", b =>
                {
                    b.Property<int>("FileDescriptionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ClaimId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<byte?>("DecisionReference");

                    b.Property<string>("Description")
                        .HasMaxLength(750);

                    b.Property<int?>("DescriptionBy");

                    b.Property<byte>("DescriptionCategory");

                    b.Property<byte?>("DescriptionCode");

                    b.Property<bool?>("Discussed");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<byte?>("FileMethod");

                    b.Property<byte?>("FileStatus");

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int?>("RemedyId");

                    b.Property<string>("Title")
                        .HasMaxLength(100);

                    b.HasKey("FileDescriptionId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("DescriptionBy");

                    b.HasIndex("DisputeGuid");

                    b.HasIndex("RemedyId");

                    b.ToTable("FileDescriptions");
                });

            modelBuilder.Entity("CM.Data.Model.FilePackage", b =>
                {
                    b.Property<int>("FilePackageId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<string>("CreatedByAccessCode")
                        .HasMaxLength(10);

                    b.Property<int?>("CreatedById");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int?>("CreatedParticipantParticipantId");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<int?>("DisputeId");

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("PackageDescription")
                        .HasMaxLength(10000);

                    b.Property<string>("PackageTitle")
                        .HasMaxLength(100);

                    b.Property<byte?>("PackageType");

                    b.HasKey("FilePackageId");

                    b.HasIndex("CreatedParticipantParticipantId");

                    b.HasIndex("DisputeId");

                    b.ToTable("FilePackages");
                });

            modelBuilder.Entity("CM.Data.Model.Hearing", b =>
                {
                    b.Property<int>("HearingId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<byte?>("HearingComplexity");

                    b.Property<string>("HearingDetails")
                        .HasMaxLength(1500);

                    b.Property<int?>("HearingDuration");

                    b.Property<DateTime?>("HearingEnd");

                    b.Property<string>("HearingLocation")
                        .HasMaxLength(255);

                    b.Property<byte?>("HearingMethod");

                    b.Property<int?>("HearingOwner");

                    b.Property<DateTime?>("HearingStart");

                    b.Property<byte>("HearingStatus");

                    b.Property<byte?>("HearingType");

                    b.Property<bool?>("IsDeleted");

                    b.Property<string>("ModeratorDialCode")
                        .HasMaxLength(15);

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("ParticipantDialCode")
                        .HasMaxLength(15);

                    b.Property<string>("PrimaryDialInNumber")
                        .HasMaxLength(20);

                    b.Property<string>("PrimaryDialInTitle")
                        .HasMaxLength(100);

                    b.Property<string>("SecondaryDialInNumber")
                        .HasMaxLength(20);

                    b.Property<string>("SecondaryDialInTitle")
                        .HasMaxLength(100);

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(1500);

                    b.Property<bool?>("UseCustomSchedule")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool?>("UseSpecialInstructions")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<byte>("VersionNumber");

                    b.HasKey("HearingId");

                    b.HasIndex("DisputeGuid");

                    b.ToTable("Hearings");
                });

            modelBuilder.Entity("CM.Data.Model.HearingParticipation", b =>
                {
                    b.Property<int>("HearingParticipationId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int>("HearingId");

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("NameAbbreviation")
                        .HasMaxLength(10);

                    b.Property<byte?>("OtherParticipantAssociation");

                    b.Property<string>("OtherParticipantName")
                        .HasMaxLength(255);

                    b.Property<string>("OtherParticipantTitle")
                        .HasMaxLength(255);

                    b.Property<int?>("ParticipantId");

                    b.Property<string>("ParticipationComment")
                        .HasMaxLength(500);

                    b.Property<byte?>("ParticipationStatus");

                    b.HasKey("HearingParticipationId");

                    b.HasIndex("HearingId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("HearingParticipations");
                });

            modelBuilder.Entity("CM.Data.Model.IntakeQuestion", b =>
                {
                    b.Property<int>("IntakeQuestionId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("DisputeGuid");

                    b.Property<byte>("GroupId");

                    b.Property<DateTime>("ModifiedDate");

                    b.Property<string>("QuestionAnswer")
                        .HasMaxLength(6);

                    b.Property<string>("QuestionName")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("IntakeQuestionId");

                    b.HasIndex("DisputeGuid", "QuestionName")
                        .IsUnique();

                    b.ToTable("IntakeQuestions");
                });

            modelBuilder.Entity("CM.Data.Model.InternalUserProfile", b =>
                {
                    b.Property<int>("InternalUserProfileId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<int>("InternalUserId");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("ProfileDecision")
                        .HasMaxLength(255);

                    b.Property<string>("ProfileNickname")
                        .HasMaxLength(40);

                    b.Property<int?>("ProfilePictureId");

                    b.Property<byte?>("ProfileStatus");

                    b.Property<string>("ProfileTitle")
                        .HasMaxLength(70);

                    b.Property<int?>("SignatureFileId");

                    b.HasKey("InternalUserProfileId");

                    b.HasIndex("InternalUserId");

                    b.HasIndex("ProfilePictureId");

                    b.HasIndex("SignatureFileId");

                    b.ToTable("InternalUserProfiles");
                });

            modelBuilder.Entity("CM.Data.Model.InternalUserRole", b =>
                {
                    b.Property<int>("InternalUserRoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<byte>("RoleGroupId");

                    b.Property<byte?>("RoleSubtypeId");

                    b.Property<int>("UserId");

                    b.HasKey("InternalUserRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("InternalUserRoles");
                });

            modelBuilder.Entity("CM.Data.Model.LinkedFile", b =>
                {
                    b.Property<int>("LinkedFileId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("Accepted");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<int>("FileDescriptionId");

                    b.Property<int>("FileId");

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("LinkedFileId");

                    b.HasIndex("DisputeGuid");

                    b.HasIndex("FileDescriptionId");

                    b.HasIndex("FileId");

                    b.ToTable("LinkedFiles");
                });

            modelBuilder.Entity("CM.Data.Model.Maintenance", b =>
                {
                    b.Property<int>("MaintenanceId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<int>("ExpectedDurationMinutes");

                    b.Property<string>("MaintenanceTitle")
                        .HasMaxLength(255);

                    b.Property<string>("OverrideKey")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<DateTime>("StartDateTime");

                    b.Property<byte>("SystemId");

                    b.HasKey("MaintenanceId");

                    b.ToTable("Maintenance");
                });

            modelBuilder.Entity("CM.Data.Model.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<byte?>("CreatorGroupRoleId");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("NoteContent")
                        .IsRequired()
                        .HasMaxLength(1500);

                    b.Property<int?>("NoteLinkId");

                    b.Property<byte>("NoteLinkedTo")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue((byte)0);

                    b.Property<byte>("NoteStatus")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue((byte)1);

                    b.Property<byte>("NoteType");

                    b.HasKey("NoteId");

                    b.HasIndex("DisputeGuid");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("CM.Data.Model.Notice", b =>
                {
                    b.Property<int>("NoticeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<int?>("HearingId");

                    b.Property<byte?>("HearingType");

                    b.Property<bool?>("IsDeleted");

                    b.Property<bool?>("IsInitialDisputeNotice");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<DateTime?>("NoticeDeliveredDate");

                    b.Property<int?>("NoticeDeliveredTo");

                    b.Property<byte?>("NoticeDeliveryMethod");

                    b.Property<int?>("NoticeFile1Id");

                    b.Property<int?>("NoticeFile2Id");

                    b.Property<int?>("NoticeFile3Id");

                    b.Property<int?>("NoticeFile4Id");

                    b.Property<int?>("NoticeFile5Id");

                    b.Property<string>("NoticeHtmlForPdf");

                    b.Property<string>("NoticeSpecialInstructions")
                        .HasMaxLength(1500);

                    b.Property<string>("NoticeTitle")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<byte>("NoticeType");

                    b.Property<byte?>("NoticeVersion")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue((byte)0);

                    b.HasKey("NoticeId");

                    b.HasIndex("DisputeGuid");

                    b.HasIndex("HearingId");

                    b.HasIndex("NoticeDeliveredTo");

                    b.HasIndex("NoticeFile1Id");

                    b.HasIndex("NoticeFile2Id");

                    b.HasIndex("NoticeFile3Id");

                    b.HasIndex("NoticeFile4Id");

                    b.HasIndex("NoticeFile5Id");

                    b.ToTable("Notices");
                });

            modelBuilder.Entity("CM.Data.Model.NoticeService", b =>
                {
                    b.Property<int>("NoticeServiceId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool?>("IsDeleted");

                    b.Property<bool?>("IsServed")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("NoticeId");

                    b.Property<byte?>("OtherParticipantRole");

                    b.Property<string>("OtherParticpantTitle")
                        .HasMaxLength(255);

                    b.Property<int>("ParticipantId");

                    b.Property<DateTime?>("ReceivedDate");

                    b.Property<int?>("ServedBy");

                    b.Property<string>("ServiceComment")
                        .HasMaxLength(255);

                    b.Property<DateTime?>("ServiceDate");

                    b.Property<byte?>("ServiceDateUsed");

                    b.Property<byte?>("ServiceMethod");

                    b.HasKey("NoticeServiceId");

                    b.HasIndex("NoticeId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("NoticeServices");
                });

            modelBuilder.Entity("CM.Data.Model.OutcomeDocContent", b =>
                {
                    b.Property<int>("OutcomeDocContentId")
                        .ValueGeneratedOnAdd();

                    b.Property<byte?>("ContentStatus");

                    b.Property<byte?>("ContentSubType");

                    b.Property<byte>("ContentType");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("OutcomeDocFileId");

                    b.Property<string>("StoredContent");

                    b.HasKey("OutcomeDocContentId");

                    b.HasIndex("OutcomeDocFileId");

                    b.ToTable("OutcomeDocContents");
                });

            modelBuilder.Entity("CM.Data.Model.OutcomeDocDelivery", b =>
                {
                    b.Property<int>("OutcomeDocDeliveryId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("ConfirmedReceived");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("DeliveryComment")
                        .HasMaxLength(500);

                    b.Property<DateTime?>("DeliveryDate");

                    b.Property<byte?>("DeliveryMethod");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<bool?>("IsDelivered");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("OutcomeDocFileId");

                    b.Property<int>("ParticipantId");

                    b.Property<DateTime?>("ReceivedDate");

                    b.HasKey("OutcomeDocDeliveryId");

                    b.HasIndex("DisputeGuid");

                    b.HasIndex("OutcomeDocFileId");

                    b.HasIndex("ParticipantId");

                    b.ToTable("OutcomeDocDeliveries");
                });

            modelBuilder.Entity("CM.Data.Model.OutcomeDocFile", b =>
                {
                    b.Property<int>("OutcomeDocFileId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<string>("FileAcronym")
                        .HasMaxLength(5);

                    b.Property<string>("FileDescription")
                        .HasMaxLength(500);

                    b.Property<int?>("FileId");

                    b.Property<byte?>("FileSource");

                    b.Property<byte?>("FileStatus");

                    b.Property<byte?>("FileSubStatus");

                    b.Property<string>("FileTitle")
                        .HasMaxLength(100);

                    b.Property<byte>("FileType");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("OutcomeDocGroupId");

                    b.Property<bool?>("VisibleToPublic")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.HasKey("OutcomeDocFileId");

                    b.HasIndex("DisputeGuid");

                    b.HasIndex("FileId");

                    b.HasIndex("OutcomeDocGroupId");

                    b.ToTable("OutcomeDocFiles");
                });

            modelBuilder.Entity("CM.Data.Model.OutcomeDocGroup", b =>
                {
                    b.Property<int>("OutcomeDocGroupId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<DateTime?>("DocCompletedDate");

                    b.Property<byte?>("DocGroupSubType");

                    b.Property<byte?>("DocGroupType");

                    b.Property<byte?>("DocStatus")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue((byte)1);

                    b.Property<DateTime?>("DocStatusDate");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.HasKey("OutcomeDocGroupId");

                    b.HasIndex("DisputeGuid");

                    b.ToTable("OutcomeDocGroups");
                });

            modelBuilder.Entity("CM.Data.Model.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AcceptedTOU");

                    b.Property<DateTime?>("AcceptedTOUDate");

                    b.Property<string>("AccessCode")
                        .HasMaxLength(10);

                    b.Property<string>("Address")
                        .HasMaxLength(125);

                    b.Property<string>("BusinessContactFirstName")
                        .HasMaxLength(50);

                    b.Property<string>("BusinessContactLastName")
                        .HasMaxLength(70);

                    b.Property<string>("BusinessName")
                        .HasMaxLength(100);

                    b.Property<string>("City")
                        .HasMaxLength(50);

                    b.Property<string>("Country")
                        .HasMaxLength(50);

                    b.Property<byte?>("CountryId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<bool?>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("Fax")
                        .HasMaxLength(15);

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsAmended");

                    b.Property<bool?>("IsDeleted");

                    b.Property<string>("LastName")
                        .HasMaxLength(70);

                    b.Property<string>("MailAddres")
                        .HasMaxLength(125);

                    b.Property<string>("MailCity")
                        .HasMaxLength(50);

                    b.Property<string>("MailCountry")
                        .HasMaxLength(50);

                    b.Property<string>("MailPostalZip")
                        .HasMaxLength(15);

                    b.Property<string>("MailProvinceState")
                        .HasMaxLength(50);

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("NameAbbreviation")
                        .HasMaxLength(10);

                    b.Property<bool?>("NoEmail")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<byte?>("PackageDeliveryMethod");

                    b.Property<byte>("ParticipantStatus")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue((byte)1);

                    b.Property<byte?>("ParticipantType");

                    b.Property<string>("PostalZip")
                        .HasMaxLength(15);

                    b.Property<byte?>("PrimaryContactMethod");

                    b.Property<string>("PrimaryPhone")
                        .HasMaxLength(15);

                    b.Property<string>("PrimaryPhoneExtension")
                        .HasMaxLength(4);

                    b.Property<byte?>("PrimaryPhoneType");

                    b.Property<bool?>("PrimaryPhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<string>("ProvinceState")
                        .HasMaxLength(50);

                    b.Property<byte?>("ProvinceStateId");

                    b.Property<string>("SecondaaryPhone")
                        .HasMaxLength(15);

                    b.Property<byte?>("SecondaryContactMethod");

                    b.Property<string>("SecondaryPhoneExtension")
                        .HasMaxLength(4);

                    b.Property<byte?>("SecondaryPhoneType");

                    b.Property<bool?>("SecondaryPhoneVerified")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<int?>("SystemUserId");

                    b.HasKey("ParticipantId");

                    b.HasIndex("DisputeGuid");

                    b.HasIndex("SystemUserId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("CM.Data.Model.PaymentTransaction", b =>
                {
                    b.Property<int>("PaymentTransactionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CardType")
                        .HasColumnType("char(2)");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("DisplayMsg")
                        .HasMaxLength(100);

                    b.Property<int>("DisputeFeeid");

                    b.Property<byte?>("FeeWaiverCitySize");

                    b.Property<decimal?>("FeeWaiverIncome")
                        .HasColumnType("decimal(10,2)");

                    b.Property<byte?>("FeeWaiverTenantsFamily");

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("OfficePaymentIdir")
                        .HasMaxLength(50);

                    b.Property<byte?>("PaymentProvider");

                    b.Property<byte?>("PaymentStatus");

                    b.Property<string>("PaymentUrl")
                        .HasMaxLength(1000);

                    b.Property<byte?>("PaymentVerified");

                    b.Property<byte?>("PaymentVerifyRetries");

                    b.Property<decimal?>("TransactionAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("TransactionBy");

                    b.Property<byte>("TransactionMethod")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(null);

                    b.Property<bool>("TrnApproved");

                    b.Property<DateTime?>("TrnDate");

                    b.Property<string>("TrnId")
                        .HasMaxLength(10);

                    b.Property<DateTime?>("TrnReqDate");

                    b.Property<int?>("TrnResponse");

                    b.Property<string>("TrnType")
                        .HasMaxLength(3);

                    b.HasKey("PaymentTransactionId");

                    b.HasIndex("DisputeFeeid");

                    b.HasIndex("TransactionBy");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("CM.Data.Model.Remedy", b =>
                {
                    b.Property<int>("RemedyId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AwardDetails")
                        .HasMaxLength(255);

                    b.Property<decimal?>("AwardedAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("AwardedDate");

                    b.Property<int?>("AwardedDaysAfterService");

                    b.Property<int>("ClaimId");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<bool?>("IsAmended");

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<byte?>("RemedySource");

                    b.Property<string>("RemedyStatsReason")
                        .HasMaxLength(255);

                    b.Property<byte?>("RemedyStatus");

                    b.Property<byte?>("RemedySubStatus");

                    b.Property<string>("RemedyTitle")
                        .HasMaxLength(150);

                    b.Property<byte?>("RemedyType");

                    b.HasKey("RemedyId");

                    b.HasIndex("ClaimId");

                    b.ToTable("Remedies");
                });

            modelBuilder.Entity("CM.Data.Model.RemedyDetail", b =>
                {
                    b.Property<int>("RemedyDetailId")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("Description")
                        .HasMaxLength(500);

                    b.Property<int>("DescriptionBy");

                    b.Property<bool?>("IsAmended");

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<int>("RemedyId");

                    b.HasKey("RemedyDetailId");

                    b.HasIndex("DescriptionBy");

                    b.HasIndex("RemedyId");

                    b.ToTable("RemedyDetails");
                });

            modelBuilder.Entity("CM.Data.Model.SystemSettings", b =>
                {
                    b.Property<int>("SystemSettingsId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Key");

                    b.Property<byte>("Type");

                    b.Property<string>("Value");

                    b.HasKey("SystemSettingsId");

                    b.ToTable("SystemSettings");
                });

            modelBuilder.Entity("CM.Data.Model.SystemUser", b =>
                {
                    b.Property<int>("SystemUserId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("AcceptsTextMessages");

                    b.Property<string>("AccountEmail")
                        .HasMaxLength(100);

                    b.Property<string>("AccountMobile")
                        .HasMaxLength(15);

                    b.Property<bool>("AdminAccess");

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("FullName")
                        .HasMaxLength(100);

                    b.Property<bool?>("IsActive");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<string>("Password")
                        .HasMaxLength(250);

                    b.Property<int>("SystemUserRoleId");

                    b.Property<Guid>("UserGuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("SystemUserId");

                    b.HasIndex("SystemUserRoleId");

                    b.ToTable("SystemUsers");
                });

            modelBuilder.Entity("CM.Data.Model.SystemUserRole", b =>
                {
                    b.Property<int>("SystemUserRoleId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RoleDescritption")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("SessionDuration")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(900);

                    b.HasKey("SystemUserRoleId");

                    b.ToTable("SystemUserRoles");
                });

            modelBuilder.Entity("CM.Data.Model.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CreatedBy");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<DateTime?>("DateTaskCompleted");

                    b.Property<Guid>("DisputeGuid");

                    b.Property<bool?>("IsDeleted");

                    b.Property<int?>("ModifiedBy");

                    b.Property<DateTime?>("ModifiedDate");

                    b.Property<DateTime?>("TaskDueDate");

                    b.Property<int?>("TaskLinkId");

                    b.Property<byte>("TaskLinkedTo")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue((byte)0);

                    b.Property<int?>("TaskOwnerId");

                    b.Property<byte>("TaskPriority")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue((byte)1);

                    b.Property<byte?>("TaskStatus");

                    b.Property<string>("TaskText")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<byte?>("TaskType");

                    b.HasKey("TaskId");

                    b.HasIndex("DisputeGuid");

                    b.HasIndex("TaskOwnerId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("CM.Data.Model.UserToken", b =>
                {
                    b.Property<int>("UserTokenId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthToken")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<DateTime>("ExpiresOn");

                    b.Property<DateTime>("IssuedOn");

                    b.Property<int?>("ParticipantId");

                    b.Property<Guid?>("SystemUserGuid");

                    b.Property<int?>("SystemUserId");

                    b.HasKey("UserTokenId");

                    b.HasIndex("SystemUserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("CM.Data.Model.Amendment", b =>
                {
                    b.HasOne("CM.Data.Model.Participant", "Participant")
                        .WithMany("Amendments")
                        .HasForeignKey("AmendmentSubmitterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("Amendments")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.Notice", "Notice")
                        .WithMany("Amendments")
                        .HasForeignKey("NoticeId");
                });

            modelBuilder.Entity("CM.Data.Model.AuditLog", b =>
                {
                    b.HasOne("CM.Data.Model.Participant", "SubmitterParticipant")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SubmitterParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.SystemUser", "SystemUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SubmitterUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CM.Data.Model.Claim", b =>
                {
                    b.HasOne("CM.Data.Model.ClaimGroup", "ClaimGroup")
                        .WithMany("Claims")
                        .HasForeignKey("ClaimGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.ClaimDetail", b =>
                {
                    b.HasOne("CM.Data.Model.Claim", "Claim")
                        .WithMany("ClaimDetails")
                        .HasForeignKey("ClaimId");

                    b.HasOne("CM.Data.Model.Participant", "Participant")
                        .WithMany("ClaimDetails")
                        .HasForeignKey("DescriptionBy")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.ClaimGroup", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("ClaimGroups")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CM.Data.Model.ClaimGroupParticipant", b =>
                {
                    b.HasOne("CM.Data.Model.ClaimGroup", "ClaimGroup")
                        .WithMany("ClaimGroupParticipants")
                        .HasForeignKey("ClaimGroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("ClaimGroupParticipants")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.Participant", "Participant")
                        .WithMany("ClaimGroupParticipants")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.Dispute", b =>
                {
                    b.HasOne("CM.Data.Model.SystemUser", "SystemUser")
                        .WithMany("Disputes")
                        .HasForeignKey("OwnerSystemUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CM.Data.Model.DisputeFee", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("DisputeFees")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.DisputeStatus", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("DisputeStatuses")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.DisputeUser", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("DisputeUsers")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CM.Data.Model.Participant", "Participant")
                        .WithMany("DisputeUsers")
                        .HasForeignKey("ParticipantId");

                    b.HasOne("CM.Data.Model.SystemUser", "SystemUser")
                        .WithMany("DisputeUsers")
                        .HasForeignKey("SystemUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.EmailAttachment", b =>
                {
                    b.HasOne("CM.Data.Model.CommonFile", "CommonFile")
                        .WithMany("EmailAttachments")
                        .HasForeignKey("CommonFileId");

                    b.HasOne("CM.Data.Model.EmailMessage", "EmailMessage")
                        .WithMany("EmailAttachments")
                        .HasForeignKey("EmailMessageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CM.Data.Model.File", "File")
                        .WithMany("EmailAttachments")
                        .HasForeignKey("FileId");
                });

            modelBuilder.Entity("CM.Data.Model.EmailMessage", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("EmailMessages")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CM.Data.Model.Participant", "Participant")
                        .WithMany("EmailMessages")
                        .HasForeignKey("ParticipantId");
                });

            modelBuilder.Entity("CM.Data.Model.File", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("Files")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CM.Data.Model.FilePackage", "FilePackage")
                        .WithMany("Files")
                        .HasForeignKey("FilePackageId");
                });

            modelBuilder.Entity("CM.Data.Model.FileDescription", b =>
                {
                    b.HasOne("CM.Data.Model.Claim", "Claim")
                        .WithMany("FileDescriptions")
                        .HasForeignKey("ClaimId");

                    b.HasOne("CM.Data.Model.Participant", "Participant")
                        .WithMany("FileDescriptions")
                        .HasForeignKey("DescriptionBy");

                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("FileDescriptions")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.Remedy", "Remedy")
                        .WithMany("FileDescriptions")
                        .HasForeignKey("RemedyId");
                });

            modelBuilder.Entity("CM.Data.Model.FilePackage", b =>
                {
                    b.HasOne("CM.Data.Model.Participant", "CreatedParticipant")
                        .WithMany("FilePackages")
                        .HasForeignKey("CreatedParticipantParticipantId");

                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("FilePackages")
                        .HasForeignKey("DisputeId");
                });

            modelBuilder.Entity("CM.Data.Model.Hearing", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("Hearings")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CM.Data.Model.HearingParticipation", b =>
                {
                    b.HasOne("CM.Data.Model.Hearing", "Hearing")
                        .WithMany("HearingParticipations")
                        .HasForeignKey("HearingId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CM.Data.Model.Participant", "Participant")
                        .WithMany("HearingParticipations")
                        .HasForeignKey("ParticipantId");
                });

            modelBuilder.Entity("CM.Data.Model.IntakeQuestion", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("IntakeQuestions")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.InternalUserProfile", b =>
                {
                    b.HasOne("CM.Data.Model.SystemUser", "SystemUser")
                        .WithMany("InternalUserProfiles")
                        .HasForeignKey("InternalUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.CommonFile", "CommonFileProfilePic")
                        .WithMany("InternalUserProfilesProfilePic")
                        .HasForeignKey("ProfilePictureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.CommonFile", "CommonFileSignature")
                        .WithMany("InternalUserProfilesSignature")
                        .HasForeignKey("SignatureFileId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CM.Data.Model.InternalUserRole", b =>
                {
                    b.HasOne("CM.Data.Model.SystemUser", "SystemUser")
                        .WithMany("InternalUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CM.Data.Model.LinkedFile", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("LinkedFiles")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.FileDescription", "FileDescription")
                        .WithMany("LinkedFiles")
                        .HasForeignKey("FileDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CM.Data.Model.File", "File")
                        .WithMany("LinkedFiles")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.Note", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("Notes")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CM.Data.Model.Notice", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("Notices")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.Hearing", "Hearing")
                        .WithMany("Notices")
                        .HasForeignKey("HearingId");

                    b.HasOne("CM.Data.Model.Participant", "Participant")
                        .WithMany("Notices")
                        .HasForeignKey("NoticeDeliveredTo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.File", "File1")
                        .WithMany("Notices1")
                        .HasForeignKey("NoticeFile1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.File", "File2")
                        .WithMany("Notices2")
                        .HasForeignKey("NoticeFile2Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.File", "File3")
                        .WithMany("Notices3")
                        .HasForeignKey("NoticeFile3Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.File", "File4")
                        .WithMany("Notices4")
                        .HasForeignKey("NoticeFile4Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.File", "File5")
                        .WithMany("Notices5")
                        .HasForeignKey("NoticeFile5Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CM.Data.Model.NoticeService", b =>
                {
                    b.HasOne("CM.Data.Model.Notice", "Notice")
                        .WithMany("NoticeServices")
                        .HasForeignKey("NoticeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CM.Data.Model.Participant", "Participant")
                        .WithMany("NoticeServices")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CM.Data.Model.OutcomeDocContent", b =>
                {
                    b.HasOne("CM.Data.Model.OutcomeDocFile", "OutcomeDocFile")
                        .WithMany("OutcomeDocContents")
                        .HasForeignKey("OutcomeDocFileId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.OutcomeDocDelivery", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("OutcomeDocDocDeliveries")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.OutcomeDocFile", "OutcomeDocFile")
                        .WithMany("OutcomeDocDeliveries")
                        .HasForeignKey("OutcomeDocFileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CM.Data.Model.Participant", "Participant")
                        .WithMany("OutcomeDocDeliveries")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.OutcomeDocFile", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("OutcomeDocFiles")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.File", "File")
                        .WithMany("OutcomeDocFiles")
                        .HasForeignKey("FileId");

                    b.HasOne("CM.Data.Model.OutcomeDocGroup", "OutcomeDocGroup")
                        .WithMany("OutcomeDocFiles")
                        .HasForeignKey("OutcomeDocGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.OutcomeDocGroup", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("OutcomeDocGroups")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CM.Data.Model.Participant", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("Participants")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CM.Data.Model.SystemUser", "SystemUser")
                        .WithMany("Participants")
                        .HasForeignKey("SystemUserId");
                });

            modelBuilder.Entity("CM.Data.Model.PaymentTransaction", b =>
                {
                    b.HasOne("CM.Data.Model.DisputeFee", "DisputeFee")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("DisputeFeeid")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CM.Data.Model.Participant", "Participant")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("TransactionBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CM.Data.Model.Remedy", b =>
                {
                    b.HasOne("CM.Data.Model.Claim", "Claim")
                        .WithMany("Remedies")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.RemedyDetail", b =>
                {
                    b.HasOne("CM.Data.Model.Participant", "Participant")
                        .WithMany("RemedyDetails")
                        .HasForeignKey("DescriptionBy")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CM.Data.Model.Remedy", "Remedy")
                        .WithMany("RemedyDetails")
                        .HasForeignKey("RemedyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.SystemUser", b =>
                {
                    b.HasOne("CM.Data.Model.SystemUserRole", "SystemUserRole")
                        .WithMany()
                        .HasForeignKey("SystemUserRoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CM.Data.Model.Task", b =>
                {
                    b.HasOne("CM.Data.Model.Dispute", "Dispute")
                        .WithMany("Tasks")
                        .HasForeignKey("DisputeGuid")
                        .HasPrincipalKey("DisputeGuid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CM.Data.Model.SystemUser", "SystemUser")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskOwnerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CM.Data.Model.UserToken", b =>
                {
                    b.HasOne("CM.Data.Model.SystemUser", "SystemUser")
                        .WithMany()
                        .HasForeignKey("SystemUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
