// <auto-generated />
using System;
using CM.Services.DataWarehouse.DataWarehouseDataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CM.Services.DataWarehouse.DataWarehouseDataModel.Migrations
{
    [DbContext(typeof(DataWarehouseContext))]
    partial class DataWarehouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CM.Services.DataWarehouse.DataWarehouseDataModel.Models.DimCity", b =>
                {
                    b.Property<int>("DimCityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DimCityId"));

                    b.Property<string>("CityName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CityNameSoundEx")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int?>("CityPopulation")
                        .HasColumnType("integer");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("CountryName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DateInserted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("integer");

                    b.Property<string>("ProvinceName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("integer");

                    b.Property<string>("RegionName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SubRegionId")
                        .HasColumnType("integer");

                    b.Property<string>("SubRegionName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("DimCityId");

                    b.ToTable("DimCities");
                });

            modelBuilder.Entity("CM.Services.DataWarehouse.DataWarehouseDataModel.Models.DimTime", b =>
                {
                    b.Property<int>("DimTimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DimTimeId"));

                    b.Property<DateTime>("AssociatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateInserted")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DayOfWeekId")
                        .HasColumnType("integer");

                    b.Property<int>("MonthId")
                        .HasColumnType("integer");

                    b.Property<int>("QuarterId")
                        .HasColumnType("integer");

                    b.Property<int>("WeekId")
                        .HasColumnType("integer");

                    b.Property<int>("YearId")
                        .HasColumnType("integer");

                    b.HasKey("DimTimeId");

                    b.ToTable("DimTimes");
                });

            modelBuilder.Entity("CM.Services.DataWarehouse.DataWarehouseDataModel.Models.FactDisputeSummary", b =>
                {
                    b.Property<int>("DisputeSummaryRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisputeSummaryRecordId"));

                    b.Property<int>("AccessCodeUsers")
                        .HasColumnType("integer");

                    b.Property<int>("AmendRemovedIssues")
                        .HasColumnType("integer");

                    b.Property<int>("AmendRemovedParticipants")
                        .HasColumnType("integer");

                    b.Property<int>("Amendments")
                        .HasColumnType("integer");

                    b.Property<int>("Applicants")
                        .HasColumnType("integer");

                    b.Property<int>("AssociatedOffice")
                        .HasColumnType("integer");

                    b.Property<int>("AvgDocDeliveryTimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("AvgTaskOpenTimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("AwardedAmount")
                        .HasColumnType("integer");

                    b.Property<int?>("AwardedClarifications")
                        .HasColumnType("integer");

                    b.Property<int?>("AwardedCorrections")
                        .HasColumnType("integer");

                    b.Property<int>("AwardedIssues")
                        .HasColumnType("integer");

                    b.Property<int>("AwardedMonetaryIssues")
                        .HasColumnType("integer");

                    b.Property<int>("AwardedPossessions")
                        .HasColumnType("integer");

                    b.Property<int?>("AwardedReviewConsiderations")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte?>("CreationMethod")
                        .HasColumnType("smallint");

                    b.Property<int>("CrossHearings")
                        .HasColumnType("integer");

                    b.Property<int>("DecisionsAndOrders")
                        .HasColumnType("integer");

                    b.Property<decimal>("DecisionsAndOrdersMb")
                        .HasColumnType("numeric");

                    b.Property<int>("DecisionsInterim")
                        .HasColumnType("integer");

                    b.Property<int>("DisputeCityId")
                        .HasColumnType("integer");

                    b.Property<int?>("DisputeComplexity")
                        .HasColumnType("integer");

                    b.Property<Guid>("DisputeGuid")
                        .HasColumnType("uuid");

                    b.Property<byte>("DisputeSubType")
                        .HasColumnType("smallint");

                    b.Property<byte?>("DisputeType")
                        .HasColumnType("smallint");

                    b.Property<byte?>("DisputeUrgency")
                        .HasColumnType("smallint");

                    b.Property<int>("DocumentSets")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentsDelivered")
                        .HasColumnType("integer");

                    b.Property<int>("EvidenceFiles")
                        .HasColumnType("integer");

                    b.Property<int>("EvidenceFilesFromApplicant")
                        .HasColumnType("integer");

                    b.Property<int>("EvidenceFilesFromRespondent")
                        .HasColumnType("integer");

                    b.Property<decimal>("EvidenceFilesMb")
                        .HasColumnType("numeric");

                    b.Property<int>("EvidenceFilesMbFromApplicant")
                        .HasColumnType("integer");

                    b.Property<int>("EvidenceFilesMbFromRespondent")
                        .HasColumnType("integer");

                    b.Property<int>("EvidenceOverrides")
                        .HasColumnType("integer");

                    b.Property<int>("EvidencePackageServices")
                        .HasColumnType("integer");

                    b.Property<int>("EvidencePackages")
                        .HasColumnType("integer");

                    b.Property<int>("EvidencePackagesFromApplicant")
                        .HasColumnType("integer");

                    b.Property<int>("EvidencePackagesFromRespondent")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FirstDecisionDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("FirstDecisionDateTimeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FirstParticipatoryHearingDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("FirstParticipatoryHearingDateTimeId")
                        .HasColumnType("integer");

                    b.Property<int>("HearingParticipations")
                        .HasColumnType("integer");

                    b.Property<int>("Hearings")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("InitialPaymentDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte?>("InitialPaymentMethod")
                        .HasColumnType("smallint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("IsAdjourned")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("Issues")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastParticipatoryHearingDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LastParticipatoryHearingTimeId")
                        .HasColumnType("integer");

                    b.Property<int?>("LastProcess")
                        .HasColumnType("integer");

                    b.Property<int?>("LastStage")
                        .HasColumnType("integer");

                    b.Property<int>("LastStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastStatusDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LastStatusTimeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LoadDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte?>("MigrationSourceOfTruth")
                        .HasColumnType("smallint");

                    b.Property<int>("Notes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NoticeDeliveredDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("NoticeDeliveredTimeId")
                        .HasColumnType("integer");

                    b.Property<int>("NoticeServices")
                        .HasColumnType("integer");

                    b.Property<int>("Notices")
                        .HasColumnType("integer");

                    b.Property<int>("OrdersMonetary")
                        .HasColumnType("integer");

                    b.Property<int>("OrdersPossession")
                        .HasColumnType("integer");

                    b.Property<int>("Participants")
                        .HasColumnType("integer");

                    b.Property<int?>("PaymentTimeId")
                        .HasColumnType("integer");

                    b.Property<int>("Payments")
                        .HasColumnType("integer");

                    b.Property<decimal>("PaymentsAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("Processes")
                        .HasColumnType("integer");

                    b.Property<int>("RequestedAmount")
                        .HasColumnType("integer");

                    b.Property<int?>("RequestedClarifications")
                        .HasColumnType("integer");

                    b.Property<int?>("RequestedCorrections")
                        .HasColumnType("integer");

                    b.Property<int?>("RequestedReviewConsideration")
                        .HasColumnType("integer");

                    b.Property<int>("Respondents")
                        .HasColumnType("integer");

                    b.Property<int>("SentEmailMessages")
                        .HasColumnType("integer");

                    b.Property<int>("Statuses")
                        .HasColumnType("integer");

                    b.Property<int>("SubServiceRequests")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SubmittedTimeId")
                        .HasColumnType("integer");

                    b.Property<int>("Tasks")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TenancyEndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("TenancyEnded")
                        .HasColumnType("boolean");

                    b.Property<int?>("TenancyUnitType")
                        .HasColumnType("integer");

                    b.Property<int>("TotalArbOwners")
                        .HasColumnType("integer");

                    b.Property<int>("TotalArbTimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCitizenStatusTimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalHearingPrepTimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalHearingTimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalIoOwners")
                        .HasColumnType("integer");

                    b.Property<int>("TotalIoTimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalOpenTimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStage0TimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStage10TimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStage2TimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStage4TimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStage6TimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStage8TimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStatus102TimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStatus22TimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalStatus41TimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWritingTimeMin")
                        .HasColumnType("integer");

                    b.Property<int>("Transactions")
                        .HasColumnType("integer");

                    b.HasKey("DisputeSummaryRecordId");

                    b.HasIndex("LoadDateTime");

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("LoadDateTime"), new[] { "CreationMethod" });

                    b.ToTable("FactDisputeSummaries");
                });

            modelBuilder.Entity("CM.Services.DataWarehouse.DataWarehouseDataModel.Models.FactHearingSummary", b =>
                {
                    b.Property<int>("HearingSummaryRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HearingSummaryRecordId"));

                    b.Property<int?>("AllLinkedEvidenceFiles")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AllLinkedEvidenceFilesMb")
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("AllLinkedIssueCodes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("AllLinkedIssues")
                        .HasColumnType("integer");

                    b.Property<int?>("AllLinkedRequestedAmount")
                        .HasColumnType("integer");

                    b.Property<int>("AssociatedOffice")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DisputeGuid")
                        .HasColumnType("uuid");

                    b.Property<int?>("HearingAttendingApplicants")
                        .HasColumnType("integer");

                    b.Property<int?>("HearingAttendingRespondents")
                        .HasColumnType("integer");

                    b.Property<int?>("HearingDuration")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HearingEndDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HearingId")
                        .HasColumnType("integer");

                    b.Property<int?>("HearingMethod")
                        .HasColumnType("integer");

                    b.Property<int?>("HearingOwner")
                        .HasColumnType("integer");

                    b.Property<int?>("HearingParticipations")
                        .HasColumnType("integer");

                    b.Property<int?>("HearingPrepTime")
                        .HasColumnType("integer");

                    b.Property<int?>("HearingPriority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HearingStartDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("HearingStartDateTimeId")
                        .HasColumnType("integer");

                    b.Property<int?>("HearingType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<byte?>("LinkedDisputes")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("LoadDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LocalHearingEndDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LocalHearingStartDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("PrimaryAdjourned")
                        .HasColumnType("boolean");

                    b.Property<int?>("PrimaryAmendments")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryApplicants")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryCreationMethod")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryDisputeSubType")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryDisputeType")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryDisputeUrgency")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryHearings")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PrimaryInitialPaymentDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PrimaryInitialPaymentTimeId")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryLastProcess")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryLastStage")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryLastStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryParticipants")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryPreviousHearingId")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryProcesses")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryRespondents")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimarySentEmailMessages")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryStatuses")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimarySubServiceRequests")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PrimarySubmittedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PrimarySubmittedTimeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PrimaryTenancyEndDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("PrimaryTenancyEnded")
                        .HasColumnType("boolean");

                    b.Property<int?>("PrimaryTenancyUnitType")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryTimeSinceInitialPaymentMin")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryTimeSinceSubmittedMin")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryTotalArbOwners")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryTotalArbTimeMin")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryTotalStage6TimeMin")
                        .HasColumnType("integer");

                    b.Property<int?>("PrimaryTotalStage8TimeMin")
                        .HasColumnType("integer");

                    b.Property<string>("SecondaryDisputeGuids")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<byte?>("SharedHearingLinkingType")
                        .HasColumnType("smallint");

                    b.HasKey("HearingSummaryRecordId");

                    b.ToTable("FactHearingSummaries");
                });

            modelBuilder.Entity("CM.Services.DataWarehouse.DataWarehouseDataModel.Models.FactIntakeProcessing", b =>
                {
                    b.Property<int>("IntakeProcessingRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IntakeProcessingRecordId"));

                    b.Property<int?>("Applicants")
                        .HasColumnType("integer");

                    b.Property<int>("AssociatedOffice")
                        .HasColumnType("integer");

                    b.Property<int?>("ConfirmingInfoStatusTimeMin")
                        .HasColumnType("integer");

                    b.Property<int?>("CreationMethod")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DisputeGuid")
                        .HasColumnType("uuid");

                    b.Property<int?>("DisputeHearingRole")
                        .HasColumnType("integer");

                    b.Property<int?>("DisputeSubType")
                        .HasColumnType("integer");

                    b.Property<int?>("DisputeType")
                        .HasColumnType("integer");

                    b.Property<int?>("DisputeUrgency")
                        .HasColumnType("integer");

                    b.Property<int?>("EvidenceFiles")
                        .HasColumnType("integer");

                    b.Property<int?>("EvidenceFilesMb")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FirstAssignedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("FirstAssignedDisputeStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("FirstAssignedOwner")
                        .HasColumnType("integer");

                    b.Property<int?>("FirstAssignedStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HearingStartDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("InitialPaymentDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("InitialPaymentMethod")
                        .HasColumnType("integer");

                    b.Property<bool?>("IntakeWasUpdated")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int?>("Issues")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastAssignedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LastAssignedDisputeStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("LastAssignedOwner")
                        .HasColumnType("integer");

                    b.Property<int?>("LastAssignedStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("LinkedDisputes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LoadDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Participants")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcessDecReqStatusAssignedTimeMin")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcessDecReqStatusTimeMin")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProcessEndDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ProcessEndDisputeStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcessEndProcess")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcessEndStage")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcessEndStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProcessStartDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ProcessStartDisputeStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcessStartProcess")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcessStartStage")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcessStartStatus")
                        .HasColumnType("integer");

                    b.Property<int?>("Processes")
                        .HasColumnType("integer");

                    b.Property<int?>("ProcessingOwners")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessingOwnersList")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<int?>("Respondents")
                        .HasColumnType("integer");

                    b.Property<int?>("ScreenDecReqStatusAssignedTimeMin")
                        .HasColumnType("integer");

                    b.Property<int?>("ScreenDecReqStatusTimeMin")
                        .HasColumnType("integer");

                    b.Property<int?>("SharedHearingLinkingType")
                        .HasColumnType("integer");

                    b.Property<int?>("Statuses")
                        .HasColumnType("integer");

                    b.Property<int?>("SubServiceRequests")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmittedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TenancyEndDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("TenancyEnded")
                        .HasColumnType("boolean");

                    b.Property<int?>("TenancyUnitType")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeIoAssignedMin")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeStatusNeedsUpdateMin")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeTotalProcessingMin")
                        .HasColumnType("integer");

                    b.Property<int?>("UnassignedStage2TimeMin")
                        .HasColumnType("integer");

                    b.HasKey("IntakeProcessingRecordId");

                    b.HasIndex("DisputeGuid", "ProcessStartDisputeStatusId", "ProcessEndDisputeStatusId")
                        .IsUnique();

                    b.ToTable("FactIntakeProcessings");
                });

            modelBuilder.Entity("CM.Services.DataWarehouse.DataWarehouseDataModel.Models.FactTimeStatistic", b =>
                {
                    b.Property<int>("DisputeSummaryRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisputeSummaryRecordId"));

                    b.Property<int>("AmendmentsSubmitted")
                        .HasColumnType("integer");

                    b.Property<int>("ArbIncompleteTasksAssigned")
                        .HasColumnType("integer");

                    b.Property<int>("ArbIncompleteTasksUnassigned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ArbIncompleteTasksUnassignedOldest")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ArbTasksCompleted")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssociatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("AssociatedDateId")
                        .HasColumnType("integer");

                    b.Property<int>("AssociatedOffice")
                        .HasColumnType("integer");

                    b.Property<decimal>("AvgNext10DeferredEmptyHearingDays")
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("AvgNext10EmergEmptyHearingDays")
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("AvgNext10StandardEmptyHearingDays")
                        .HasColumnType("numeric(6,2)");

                    b.Property<int>("ClarificationRequests")
                        .HasColumnType("integer");

                    b.Property<int>("CorrectionRequests")
                        .HasColumnType("integer");

                    b.Property<int>("DeferredDisputesPaid")
                        .HasColumnType("integer");

                    b.Property<int>("DisputeHearings")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentsDelivered")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentsUndelivered")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DocumentsUndeliveredOldest")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DocumentsUndeliveredUrgent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DocumentsUndeliveredUrgentOldest")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EmergencyDisputesPaid")
                        .HasColumnType("integer");

                    b.Property<int>("EmptyHearings")
                        .HasColumnType("integer");

                    b.Property<int>("EvidenceFiles")
                        .HasColumnType("integer");

                    b.Property<int>("EvidenceFilesMb")
                        .HasColumnType("integer");

                    b.Property<int>("Files")
                        .HasColumnType("integer");

                    b.Property<int>("FilesMb")
                        .HasColumnType("integer");

                    b.Property<int>("IntakePayments")
                        .HasColumnType("integer");

                    b.Property<int?>("IntakeProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("IoIncompleteTasksAssigned")
                        .HasColumnType("integer");

                    b.Property<int>("IoIncompleteTasksUnassigned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("IoIncompleteTasksUnassignedOldest")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IoTasksCompleted")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int>("LandlordDisputesPaid")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LoadDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("OfficeDisputesPaid")
                        .HasColumnType("integer");

                    b.Property<int>("OnlineDisputesPaid")
                        .HasColumnType("integer");

                    b.Property<int>("OpenFiles")
                        .HasColumnType("integer");

                    b.Property<int>("OtherIncompleteTasks")
                        .HasColumnType("integer");

                    b.Property<int>("PerUnitPayments")
                        .HasColumnType("integer");

                    b.Property<int>("Process1DisputesPaid")
                        .HasColumnType("integer");

                    b.Property<int>("Process2DisputesPaid")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewPayments")
                        .HasColumnType("integer");

                    b.Property<int>("ReviewRequests")
                        .HasColumnType("integer");

                    b.Property<int>("Stage0Open")
                        .HasColumnType("integer");

                    b.Property<int>("Stage10Open")
                        .HasColumnType("integer");

                    b.Property<int>("Stage2Assigned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Stage2AssignedOldest")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Stage2Open")
                        .HasColumnType("integer");

                    b.Property<int>("Stage2Unassigned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Stage2UnassignedOldest")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Stage4Open")
                        .HasColumnType("integer");

                    b.Property<int>("Stage6Open")
                        .HasColumnType("integer");

                    b.Property<int>("Stage8Open")
                        .HasColumnType("integer");

                    b.Property<int>("StandardDisputesPaid")
                        .HasColumnType("integer");

                    b.Property<byte>("StatisticsType")
                        .HasColumnType("smallint");

                    b.Property<int>("StatusAbandonedNeedsUpdate")
                        .HasColumnType("integer");

                    b.Property<int>("StatusAbandonedNoService")
                        .HasColumnType("integer");

                    b.Property<int>("StatusCancelled")
                        .HasColumnType("integer");

                    b.Property<int>("StatusClosed")
                        .HasColumnType("integer");

                    b.Property<int>("StatusNeedsUpdate")
                        .HasColumnType("integer");

                    b.Property<int>("StatusRescheduledAssigned")
                        .HasColumnType("integer");

                    b.Property<int>("StatusRescheduledUnassigned")
                        .HasColumnType("integer");

                    b.Property<int>("StatusWaitingForDecision")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StatusWaitingForDecisionOldest")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("StatusWaitingProofService")
                        .HasColumnType("integer");

                    b.Property<int>("StatusWithdrawn")
                        .HasColumnType("integer");

                    b.Property<int>("SubServicesSubmitted")
                        .HasColumnType("integer");

                    b.Property<int>("TenantDisputesPaid")
                        .HasColumnType("integer");

                    b.HasKey("DisputeSummaryRecordId");

                    b.ToTable("FactTimeStatistics");
                });

            modelBuilder.Entity("CM.Services.DataWarehouse.DataWarehouseDataModel.Models.LoadingHistory", b =>
                {
                    b.Property<int>("LoadingEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LoadingEventId"));

                    b.Property<int>("FactTableId")
                        .HasColumnType("integer");

                    b.Property<string>("FactTableName")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<int>("LastStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LoadEndDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LoadStartDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OutcomeText")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("TotalRecordsLoaded")
                        .HasColumnType("integer");

                    b.HasKey("LoadingEventId");

                    b.ToTable("LoadingHistories");
                });

            modelBuilder.Entity("CM.Services.DataWarehouse.DataWarehouseDataModel.Models.SystemUser", b =>
                {
                    b.Property<int>("SystemUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SystemUserId"));

                    b.Property<string>("AccountEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SystemUserId");

                    b.ToTable("SystemUsers");
                });

            modelBuilder.Entity("CM.Services.DataWarehouse.DataWarehouseDataModel.Models.UserToken", b =>
                {
                    b.Property<int>("UserTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserTokenId"));

                    b.Property<string>("AuthToken")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("IssuedOn")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SystemUserId")
                        .HasColumnType("integer");

                    b.HasKey("UserTokenId");

                    b.HasIndex("SystemUserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("CM.Services.DataWarehouse.DataWarehouseDataModel.Models.UserToken", b =>
                {
                    b.HasOne("CM.Services.DataWarehouse.DataWarehouseDataModel.Models.SystemUser", "SystemUser")
                        .WithMany()
                        .HasForeignKey("SystemUserId");

                    b.Navigation("SystemUser");
                });
#pragma warning restore 612, 618
        }
    }
}
