FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base

WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

COPY ["CM.Services/EmailNotification/EmailNotificationService/EmailNotificationService.csproj", "CM.Services/EmailNotification/EmailNotificationService/"]
COPY ["CM.Common.Utilities/CM.Common.Utilities.csproj", "CM.Common.Utilities/"]
COPY ["CM.Messages/CM.Messages.csproj", "CM.Messages/"]

RUN dotnet restore "CM.Services/EmailNotification/EmailNotificationService/EmailNotificationService.csproj"
COPY . .
RUN dotnet build "CM.Services/EmailNotification/EmailNotificationService/EmailNotificationService.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CM.Services/EmailNotification/EmailNotificationService/EmailNotificationService.csproj" -c Release -o /app/publish

FROM base AS final

WORKDIR /app

COPY --from=publish /app/publish .
RUN apt-get update && apt-get install -y curl

ENTRYPOINT ["dotnet", "EmailNotificationService.dll"]
